### PR TITLE
upgrade to react 18

### LINKED ISSUE #1269: 🐛 [BUG] tooltips are throwing errors in React 18
### 🐛 bug 

After upgrading to React 18, hovering over a chart with a tooltip throws the following error:

```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
```

Looking into the code a bit I found this file: https://github.com/ant-design/ant-design-charts/blob/master/packages/plots/src/util/createNode.ts

```
// @ts-ignore
import ReactDOM from 'react-dom';
var createNode = function (children, type) {
    var mountPoint = document.createElement('div');
    if (type === 'tooltip') {
        mountPoint.className = 'g2-tooltip';
    }
    ReactDOM.render(children, mountPoint);
    return mountPoint;
};
export default createNode;
```

This is using the old way to render in reactDOM and needs to be upgraded to use React 18's createRoot method. It's a very simple upgrade to do.

Please see this short guide: https://reactjs.org/link/switch-to-createroot

### 📷

Screen Shot 2022-04-18 at 15 28 57

- ant-design-charts 版本: 1.3.6

### PR DESCRIPTION
**Pull request by MarkLyck**
fixes #1269

### CODE REVIEW

**Comment by MarkLyck** [comment]
@lxfu1 can you share some insight as to why the yarn install failed?

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@types/scheduler/-/scheduler-0.16.2.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/runner/work/ant-design-charts/ant-design-charts/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
warning url-loader@1.1.2: Invalid bin field for "url-loader".
```

Doesn't seem related to any changes in this PR 🤔

**Comment by lxfu1** [comment]
> @lxfu1 can you share some insight as to why the yarn install failed?
> 
> ```
> error An unexpected error occurred: "https://registry.yarnpkg.com/@types/scheduler/-/scheduler-0.16.2.tgz: Request failed \"404 Not Found\"".
> info If you think this is a bug, please open a bug report with the information provided in "/Users/runner/work/ant-design-charts/ant-design-charts/yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> warning url-loader@1.1.2: Invalid bin field for "url-loader".
> ```
> 
> Doesn't seem related to any changes in this PR 🤔

Deleted node_module and reinstall ?

**Comment by johnpangalos** [comment]
It seems like it could be a temporary issue with the yarn package registry.

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@types/scheduler/-/scheduler-0.16.2.tgz: Request failed \"404 Not Found\"".
```

I'd retry the test. Did you get this issue locally?

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/pull/1456

**Pull request closed without merging**
